### ISSUE TITLE
Make compatible with Build PhoneGap

### ISSUE THREAD

**Issue by benpaddlejones** [Telerik-Verified-Plugins/SendGrid#3]
Build PhoneGap is currently based on PhoneGap 3.7.0 (I believe process of moving forward). Version 1.04 can't be added in the IDE as a plugin as it's missing the description tag.

Example here: https://github.com/katzer/cordova-plugin-email-composer/blob/master/plugin.xml

**Comment by EddyVerbruggen** [comment]
Done. Does this help?

**Comment by benpaddlejones** [comment]
TY, added as a Public plugin: https://build.phonegap.com/plugins/3375

**Comment by benpaddlejones** [comment]
I just realised it's pulled form your master repo (v1.06), if Build PhoneGap is based on PhoneGap 3.7.0 your documentation says I should use v1.04, what tag or brand do I use to target that version?

**Comment by EddyVerbruggen** [comment]
Hi, that remark was for Telerik AppBuilder, I'm not sure which plugman version is being used with the 3.7.0 profile of PGB.  Does the build work? If so then you're good.
