### ISSUE TITLE
install error - com.telerik.afnetworking

### ISSUE THREAD

**Issue by whodeee** [Telerik-Verified-Plugins/SendGrid#4]
When I am trying to install this plugin with Cordova CLI I get an error during
`Fetching plugin "com.telerik.afnetworking" via cordova plugins registry` 
It says "Probably this is either a connection problem or plugin spec in incorrect.  Check your connection and plugin name/version/URL"

**Comment by EddyVerbruggen** [comment]
Note that this was fixed 18 days ago by version 1.0.7 - forgot to post back here.
