### ISSUE TITLE
No package.json

### ISSUE THREAD

**Issue by dedawg123** [Telerik-Verified-Plugins/SendGrid#8]
Unable to download plugin. Package.json not available

**Comment by EddyVerbruggen** [comment]
Would you care to PR one perhaps? It only needs a few fields to make Cordova 7 happy I think.

**Comment by dedawg123** [comment]
I tried writing one but I am very new, I don't believe it's perfect or even correct

**Comment by EddyVerbruggen** [comment]
Thanks. Please reopen if that didn't help.
